language: cpp
sudo: true
dist: trusty
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - os: linux:
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - os: osx
      compiler: clang
# we may need to install libcurl, valgrind, and the custom version of libcurl
# that is built against gnutls.
script:
  - printenv
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j4
  - ctest --output-on-failure -C Debug
