version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: debian:jessie
    working_directory: /src

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run:
          # This would be better to do via a Docker image
          name: Install dependencies
          command: |
             apt-get update
             apt-get install -y build-essential \
               libcurl4-gnutls-dev \
               valgrind \
               cmake
        
      - run:
          name: CMake configure
          command: |
            mkdir -p /tmp/build && cmake -DCMAKE_BUILD_TYPE=Debug /src

      - run:
          name: Compile the library
          command: |
            make

      - run:
          name: Run test suite
          command: |
            make test
